server:
  port: 9980

management:
  endpoints:
    web:
      exposure:
        include: '*'

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
  online:
    enabled: false
    url: http://localhost:${server.port}/

mupdf:
  max-width: 1527
  max-height: 1527