server:
  port: 9980

management:
  endpoints:
    web:
      exposure:
        include: '*'

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
  online:
    enabled: false
    url: http://192.168.60.59:${server.port}/
