server:
  port: 9980

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging:
  level:
    me.hebaceous.jodconverter.server: debug

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
  online:
    enabled: false
    url: http://192.168.60.59:9980/

mupdf:
  max-width: 1527
  max-height: 1527